# -*- coding: utf-8 -*-
"""time4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3dHEeCbIox4PaLNsCiroP-qHguvnz5a
"""

import serial
from datetime import datetime
import time

arduino = serial.Serial('COM3', 9600)  # Change to your correct port
time.sleep(2)

now = datetime.now()
formatted = now.strftime("%H:%M")
arduino.write((formatted + "\n").encode())
arduino.close()

print("Time sent:", formatted)